[platformio]
default_envs = cyd-28-font-viewer

[env:cyd-28-font-viewer]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
